### ISSUE TITLE
docker-compose fails on Mac OS and native Docker

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/docker-zipkin-dependencies#8]
```
$ gl | head -1
76c2c5f - (HEAD -> master, tag: 1.0.0, origin/master, origin/HEAD) 1.0.0 (3 days ago) <Adrian Cole>

$ docker-compose up
Creating network "dockerzipkinjava_default" with the default driver
Pulling storage (openzipkin/zipkin-mysql:1.40.1)...
1.40.1: Pulling from openzipkin/zipkin-mysql
4d06f2521e4f: Pull complete
0cb4d0235f08: Pull complete
a3ed95caeb02: Pull complete
ce2f84063b3c: Pull complete
b2a99ff90f84: Pull complete
dc5e5b4460aa: Pull complete
78ff4111b0dd: Pull complete
252a69b0723c: Pull complete
18ca7fdb0f2c: Pull complete
473c6203e315: Pull complete
8527d66d7e22: Pull complete
1b6e955f0772: Pull complete
6e791ff6c9e3: Pull complete
Digest: sha256:da3fa4b8ade100a427e517b88bd85b8edcb6949586d15d1e05502e4c6244ea73
Status: Downloaded newer image for openzipkin/zipkin-mysql:1.40.1
Pulling server (openzipkin/zipkin-java:1.0.0)...
1.0.0: Pulling from openzipkin/zipkin-java
4d06f2521e4f: Already exists
93bf0c6c4f8d: Pull complete
a3ed95caeb02: Pull complete
37ce3d39dcb0: Pull complete
7723f9391196: Pull complete
Digest: sha256:9229f95cabceed8a1f20372fd9786b2e9db6224c9bb33c07b0a3cee1a5fe8b4a
Status: Downloaded newer image for openzipkin/zipkin-java:1.0.0
Creating mysql

ERROR: for storage  driver failed programming external connectivity on endpoint mysql (34ee6069ac205e5d1989f3193e988c67bd894754a16665b0462d45744aa42604): Error starting userland proxy: Failed to bind SOCK_STREAM 0.0.0.0:3306 Unix.Unix_error(Unix.EADDRINUSE, "bind", "")
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

**Comment by yurishkuro** [comment]
![image](https://cloud.githubusercontent.com/assets/3523016/15628834/b7cadf3a-24d9-11e6-882c-8bc351fb7489.png)

**Comment by yurishkuro** [comment]
for comparison, the Cassandra setup runs fine

`$ docker-compose -f docker-compose-cassandra.yml up`

**Comment by yurishkuro** [comment]
oops, spoke too soon. In case of Cassandra, the servers do start, but the query server is unable to find `cassandra`:

```
server_1   | 2016-05-28 17:49:19.815 ERROR 7 --- [nio-9411-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra:9042 (com.datastax.driver.core.exceptions.TransportException: [null] Cannot connect))] with root cause
server_1   |
server_1   | com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: cassandra:9042 (com.datastax.driver.core.exceptions.TransportException: [null] Cannot connect))
```

**Comment by yurishkuro** [comment]
Was able to fix the cassandra case by using `storage` as the host name. Perhaps MacOS native Docker does not understand `container_name: cassandra`

```
$ docker exec -it 81d12b4177cd /bin/sh
/zipkin # nslookup cassandra
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'cassandra': Name does not resolve

/zipkin # nslookup storage
nslookup: can't resolve '(null)': Name does not resolve

Name:      storage
Address 1: 172.20.0.2 52e205529e58_52e205529e58_52e205529e58_cassandra.dockerzipkinjava_default
```

Fix:

```
-      - CASSANDRA_CONTACT_POINTS=cassandra
+      - CASSANDRA_CONTACT_POINTS=storage
```

**Comment by codefromthecrypt** [comment]
redirected to here https://github.com/openzipkin/docker-zipkin/issues/108
